# Generated by Django 4.1.4 on 2022-12-08 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summariser', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio',
            name='num_speakers',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
